name: production
permissions:
    id-token: write
    contents: read
on:
    push:
        branches: [main]

jobs:
    deploy:
        name: deploy to production
        environment:
            name: production
            url: https://dashboard.string.xyz
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v1.7.0
              with:
                  aws-region: us-west-2
                  role-to-assume: ${{ secrets.PROD_AWS_ASSUME_ROLE }}

            - name: setup nodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: install dependencies
              run: |
                  yarn install

            - name: generate env
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  envkey_VITE_ENV: production
                  envkey_VITE_API_URL: https://platform-api.string-api.xyz
                  envkey_VITE_PROD_DASH_URL: https://dashboard.string.xyz
                  envkey_VITE_SBOX_DASH_URL: https://sandbox.string.xyz
                  envkey_VITE_KYB_URL: ${{ secrets.KYB_URL }}
                  envkey_VITE_DOCS_URL: https://docs.string.xyz/docs
                  filename: .env
                  directory: ./

            - name: build
              run: |
                  yarn build

            - name: deploy
              run: |
                  aws s3 cp --recursive build/ s3://${{ secrets.PROD_AWS_S3_BUCKET }}
                  aws cloudfront create-invalidation --distribution-id ${{secrets.PROD_DISTRIBUTION_ID}} --paths "/*"
