name: deploy to sandbox
permissions:
  id-token: write
  contents: read
on: 
  push:
    branches: [sandbox]

jobs:
  sandbox:
    environment: 
      name: sandbox
      url: https://sandbox.string.xyz

    name: build push and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}

      - name: setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: |
          yarn install
          
      - name: generate env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_ENV: sandbox
          envkey_VITE_API_URL: https://platform-api.sandbox.string-api.xyz
          envkey_VITE_KYB_URL: ${{ secrets.KYB_URL }}
          envkey_VITE_DOCS_URL: https://docs.string.xyz/docs
          filename: .env
          directory: ./

      - name: build
        run: |
          yarn build

      - name: deploy
        run: |
          aws s3 cp --recursive build/ s3://${{ secrets.SANDBOX_AWS_S3_BUCKET }}
          aws cloudfront create-invalidation --distribution-id ${{secrets.SANDBOX_DISTRIBUTION_ID}} --paths "/*"
